[package]
name = "libfreetype-library"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
shared-library-builder = { git = "https://github.com/feenkcom/shared-library-builder-rs", features = ["git-location", "cmake-library"] }
which = "4.2"
file-matcher = "0.6"